map_type: costmap

# delay or latency allowed between transforms
transform_tolerance: 0.2

# map update loop
update_frequency: 10.0
publish_frequency: 10.0

# obstacle detected by a laser sensor is within 0.1 meters from the base of the robot, 
# that obstacle will be added to the costmap. 
# Can help discarding noise, falsely detecting obstacles, and computational costs.
obstacle_range: 3.0
# clear and update the free space in the costmap as the robot moves.
raytrace_range: 3.0
# minimum distance between the robot geometry and the obstacles
inflation_radius: 0.15

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
