global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 50.0
   publish_frequency: 50.0
   width:  15.0 # original 40.0
   height: 15.0 # original 40.0
   resolution: 0.15 # original 0.05
   static_map: true
   rolling_window: false